CREATE TABLE IF NOT EXISTS hjoin (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(32),
    UUID VARCHAR(32),
    FJC INTEGER,
    FJCONL INTEGER,
    LCDATE DATE,
    LCIP VARCHAR(16),
    FCDATE DATE,
    FCIP VARCHAR(16)
    );