CREATE TABLE IF NOT EXISTS `hjoin` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(32),
    `UUID` VARCHAR(32),
    `FJC` BOOLEAN,
    `FJCONL` BOOLEAN,
    `LCDATE` DATE,
    `LCIP` VARCHAR(16),
    `FCDATE` DATE,
    `FCIP` VARCHAR(16),
    PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `hjoinADMIN` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(32),
    `UUID` VARCHAR(32),
    `FJC` BOOLEAN,
    `FJCONL` BOOLEAN,
    `LCDATE` DATE,
    `LCIP` VARCHAR(16),
    `FCDATE` DATE,
    `FCIP` VARCHAR(16),
    PRIMARY KEY (`ID`)
);