#
#
#
#
#####================ DATABASE CONFIG ================#######
# -------TRUE = MYSQL------
# ------ FALE = SQL LITE

Version: '00.02-Alpha'
MySQL: false
server: ''
port: ''
database: ''
user: ''
password: ''
ssl: 'false'
timezone: 'UTC'
tittest: '123456'
#####================ LANGUAGE ================#######
# Language files in language folders
lang: 'PL-pl'
#####================ ADMINISTRATION CONF ================#######

#####================ ================#######
#####================ ================#######